### ISSUE TITLE
CSS Grid for `Card layout`

### ISSUE THREAD

**Issue by Xaviju** [phuoc-ng/csslayout#191]
I'd like to know why this repo is not using CSS grid for `card layout` instead of flex.

Current code displays the grid using flex as here: https://github.com/phuoc-ng/csslayout/blob/88200a698329be14ddc916053266ac788697de8f/client/patterns/card-layout/Details.tsx#L36

Instead, it would be simpler and more powerful to implement grid as:

```css
.cards {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(4, 1fr);
}
```

Am I missing something?

I'll be happy to PR this if you agree.
